services:
  - type: web
    name: manufacturing-assistant
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
      - key: ANONYMIZED_TELEMETRY
        value: "False"
      - key: CHROMA_CLIENT_TIMEOUT
        value: "60"
      - key: GOOGLE_DRIVE_FOLDER_ID
        value: "1MQIDFQHcfbJ-iAFkczXL9HtpGe2gjoqJ"
      - key: AUTO_SYNC_ON_STARTUP
        value: "true"
      - key: GDRIVE_CLIENT_CONFIG
        value: '{"installed":{"client_id":"REPLACE_WITH_YOUR_CLIENT_ID","client_secret":"REPLACE_WITH_YOUR_CLIENT_SECRET","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}'